#!/bin/sh
# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Pierre Gaufillet <pierre.gaufillet@bergamote.eu>
# /usr/lib/ha-cluster/ha-cluster.sh
# Library functions for HA cluster management

. /lib/functions.sh
. /lib/config/uci.sh

HA_CLUSTER_CONFIG="/etc/config/ha-cluster"
# Generated configs are placed in a dedicated directory to avoid conflicts
# with standalone service init scripts (which use /tmp/*.conf)
HA_CLUSTER_RUN_DIR="/tmp/ha-cluster"
KEEPALIVED_CONF="${HA_CLUSTER_RUN_DIR}/keepalived.conf"
OWSYNC_CONF="${HA_CLUSTER_RUN_DIR}/owsync.conf"
LEASE_SYNC_CONF="${HA_CLUSTER_RUN_DIR}/lease-sync.conf"

# Log level constants (matches syslog priorities)
HA_LOG_LEVEL_ERROR=0
HA_LOG_LEVEL_WARNING=1
HA_LOG_LEVEL_INFO=2
HA_LOG_LEVEL_DEBUG=3

# Current log level (default: INFO)
HA_LOG_LEVEL="${HA_LOG_LEVEL:-2}"

# Initialize log level from UCI (call once at start)
ha_log_init() {
	config_load ha-cluster
	config_get HA_LOG_LEVEL advanced log_level "2"
}

# Log error (always logged)
ha_log_error() {
	logger -t ha-cluster -p daemon.err "$@"
}

# Log warning (level >= 1)
ha_log_warning() {
	[ "$HA_LOG_LEVEL" -ge "$HA_LOG_LEVEL_WARNING" ] && \
		logger -t ha-cluster -p daemon.warning "$@"
}

# Log info (level >= 2)
ha_log_info() {
	[ "$HA_LOG_LEVEL" -ge "$HA_LOG_LEVEL_INFO" ] && \
		logger -t ha-cluster -p daemon.info "$@"
}

# Log debug (level >= 3)
ha_log_debug() {
	[ "$HA_LOG_LEVEL" -ge "$HA_LOG_LEVEL_DEBUG" ] && \
		logger -t ha-cluster -p daemon.debug "$@"
}

# Convenience wrapper (maps to info level)
ha_log() {
	ha_log_info "$@"
}

# ============================================
# Helper Functions to Reduce Code Duplication
# ============================================

# Generic list collector for config_list_foreach
# Usage: _ha_list_result=""; config_list_foreach section option _ha_list_collect; myvar="$_ha_list_result"
_ha_list_result=""
_ha_list_collect() {
	_ha_list_result="$_ha_list_result $1"
}

# Conditional append to config file
# Usage: ha_conf_append "$file" "key" "$value" ["indent"]
# Only appends if value is non-empty
ha_conf_append() {
	local file="$1"
	local key="$2"
	local value="$3"
	local indent="${4:-    }"
	[ -n "$value" ] && echo "${indent}${key} ${value}" >> "$file"
}

# Convert netmask to CIDR prefix length
# Usage: netmask_to_cidr "255.255.255.0" -> "24"
netmask_to_cidr() {
	local netmask="$1"
	local cidr=0

	# Convert each octet
	for octet in $(echo "$netmask" | tr '.' ' '); do
		case "$octet" in
			255) cidr=$((cidr + 8)) ;;
			254) cidr=$((cidr + 7)) ;;
			252) cidr=$((cidr + 6)) ;;
			248) cidr=$((cidr + 5)) ;;
			240) cidr=$((cidr + 4)) ;;
			224) cidr=$((cidr + 3)) ;;
			192) cidr=$((cidr + 2)) ;;
			128) cidr=$((cidr + 1)) ;;
			0) ;;
			*) ha_log_error "Invalid netmask octet '$octet' in '$netmask'"; return 1 ;;
		esac
	done

	echo "$cidr"
}

# Validate IPv6 address format (basic check)
# Defense-in-depth: LuCI validates on input, keepalived validates on load
# Usage: is_valid_ipv6 "fd00::1" -> returns 0 (valid) or 1 (invalid)
is_valid_ipv6() {
	local addr="$1"
	# Must contain at least one colon
	case "$addr" in
		*:*) ;;
		*) return 1 ;;
	esac
	# Length check: 2 (::) to 39 (full form)
	local len=${#addr}
	[ "$len" -lt 2 ] || [ "$len" -gt 39 ] && return 1
	# Only hex digits and colons allowed
	case "$addr" in
		*[!0-9a-fA-F:]*) return 1 ;;
	esac
	return 0
}

# Get global config value
ha_get_config() {
	local var="$1"
	local default="$2"
	config_load ha-cluster
	config_get value config "$var" "$default"
	echo "$value"
}

# Generate keepalived configuration
ha_generate_keepalived_conf() {
	local node_name node_priority enable_notifications notification_email_from smtp_server
	local max_auto_priority
	local notification_emails=""

	config_load ha-cluster
	node_name="$(cat /proc/sys/kernel/hostname)"
	config_get node_priority config node_priority "100"
	config_get max_auto_priority advanced max_auto_priority "0"
	config_get_bool enable_notifications advanced enable_notifications 0
	config_get notification_email_from advanced notification_email_from ""
	config_get smtp_server advanced smtp_server ""

	_ha_list_result=""
	config_list_foreach advanced notification_email _ha_list_collect
	notification_emails="$_ha_list_result"

	ha_log "Generating keepalived configuration for node: $node_name"

	cat > "$KEEPALIVED_CONF" <<EOF
! Keepalived configuration - Generated by ha-cluster
! DO NOT EDIT - This file is auto-generated when HA cluster is enabled
! Edit /etc/config/ha-cluster instead

global_defs {
    router_id $node_name
    dynamic_interfaces
    script_user root
    enable_script_security
    max_auto_priority $max_auto_priority
EOF

	if [ "$enable_notifications" -eq 1 ]; then
		if [ -n "$notification_emails" ]; then
			cat >> "$KEEPALIVED_CONF" <<EOF
    notification_email {
EOF
			for email in $notification_emails; do
				echo "        $email" >> "$KEEPALIVED_CONF"
			done
			cat >> "$KEEPALIVED_CONF" <<EOF
    }
EOF
		fi
		ha_conf_append "$KEEPALIVED_CONF" "notification_email_from" "$notification_email_from"
		ha_conf_append "$KEEPALIVED_CONF" "smtp_server" "$smtp_server"
	fi

	echo "}" >> "$KEEPALIVED_CONF"
	echo "" >> "$KEEPALIVED_CONF"

	# Generate VRRP scripts (health checks)
	config_foreach ha_generate_vrrp_script script

	# Generate VRRP instances
	config_foreach ha_generate_vrrp_instance vip

	ha_log "Keepalived configuration generated at $KEEPALIVED_CONF"
	return 0
}

# Generate a VRRP script block
ha_generate_vrrp_script() {
	local section="$1"
	local script interval timeout weight rise fall user

	config_get script "$section" script
	[ -z "$script" ] && return 0

	config_get interval "$section" interval "5"
	config_get timeout "$section" timeout ""
	config_get weight "$section" weight ""
	config_get rise "$section" rise ""
	config_get fall "$section" fall ""
	config_get user "$section" user ""

	cat >> "$KEEPALIVED_CONF" <<EOF
vrrp_script ${section} {
    script "$script"
    interval $interval
EOF

	ha_conf_append "$KEEPALIVED_CONF" "timeout" "$timeout"
	ha_conf_append "$KEEPALIVED_CONF" "weight" "$weight"
	ha_conf_append "$KEEPALIVED_CONF" "rise" "$rise"
	ha_conf_append "$KEEPALIVED_CONF" "fall" "$fall"
	ha_conf_append "$KEEPALIVED_CONF" "user" "$user"

	echo "}" >> "$KEEPALIVED_CONF"
	echo "" >> "$KEEPALIVED_CONF"
}

# Write common VRRP instance options (shared between IPv4 and IPv6 instances)
# Uses parent-scope variables: nopreempt, preempt_delay, garp_master_delay,
# track_ifaces, track_scripts, auth_type, auth_pass, unicast_peers, unicast_src_ip
_ha_write_vrrp_instance_options() {
	local label="$1"

	if [ "$nopreempt" -eq 1 ]; then
		echo "    nopreempt" >> "$KEEPALIVED_CONF"
	elif [ -n "$preempt_delay" ]; then
		echo "    preempt_delay $preempt_delay" >> "$KEEPALIVED_CONF"
	fi

	ha_conf_append "$KEEPALIVED_CONF" "garp_master_delay" "$garp_master_delay"

	# Track interfaces
	if [ -n "$track_ifaces" ]; then
		echo "    track_interface {" >> "$KEEPALIVED_CONF"
		for iface in $track_ifaces; do
			local resolved_iface
			if network_get_device resolved_iface "$iface" 2>/dev/null; then
				ha_log_debug "VIP $label: resolved track_interface '$iface' to device '$resolved_iface'"
				echo "        $resolved_iface" >> "$KEEPALIVED_CONF"
			else
				ha_log_debug "VIP $label: using track_interface '$iface' as-is"
				echo "        $iface" >> "$KEEPALIVED_CONF"
			fi
		done
		echo "    }" >> "$KEEPALIVED_CONF"
	fi

	# Track scripts
	if [ -n "$track_scripts" ]; then
		echo "    track_script {" >> "$KEEPALIVED_CONF"
		for script_name in $track_scripts; do
			echo "        $script_name" >> "$KEEPALIVED_CONF"
		done
		echo "    }" >> "$KEEPALIVED_CONF"
	fi

	# Authentication
	if [ "$auth_type" != "none" ] && [ -n "$auth_pass" ]; then
		cat >> "$KEEPALIVED_CONF" <<EOF
    authentication {
        auth_type $auth_type
        auth_pass "$auth_pass"
    }
EOF
	fi

	# Unicast peers
	if [ -n "$unicast_peers" ]; then
		if [ -n "$unicast_src_ip" ]; then
			ha_conf_append "$KEEPALIVED_CONF" "unicast_src_ip" "$unicast_src_ip"
		fi
		echo "    unicast_peer {" >> "$KEEPALIVED_CONF"
		for peer in $unicast_peers; do
			echo "        $peer" >> "$KEEPALIVED_CONF"
		done
		echo "    }" >> "$KEEPALIVED_CONF"
	fi
}

# Generate a VRRP instance section
ha_generate_vrrp_instance() {
	local section="$1"
	local enabled interface interface_logical address netmask address6 prefix6 vrid priority nopreempt track_interface
	local advert_int preempt_delay garp_master_delay auth_type auth_pass unicast_src_ip
	local track_ifaces="" track_scripts="" unicast_peers=""

	config_get_bool enabled "$section" enabled 0
	[ "$enabled" -eq 0 ] && return 0

	# Get interface from UCI (may be logical name like "lan" or device name like "br-lan")
	config_get interface_logical "$section" interface

	# Try to resolve to device name using OpenWrt network helpers
	# If it's already a device name, network_get_device will fail and we keep the original
	. /lib/functions/network.sh
	if network_get_device interface "$interface_logical" 2>/dev/null; then
		ha_log_debug "VIP $section: resolved interface '$interface_logical' to device '$interface'"
	else
		# Not a UCI interface, assume it's already a device name
		interface="$interface_logical"
		ha_log_debug "VIP $section: using interface '$interface' as-is (not a UCI interface name)"
	fi
	config_get address "$section" address
	config_get netmask "$section" netmask "255.255.255.0"
	config_get address6 "$section" address6 ""
	config_get prefix6 "$section" prefix6 "64"
	config_get vrid "$section" vrid
	config_get priority "$section" priority "$(ha_get_config node_priority 100)"
	config_get_bool nopreempt "$section" nopreempt 1
	config_get track_interface "$section" track_interface
	config_get advert_int "$section" advert_int "1"
	config_get preempt_delay "$section" preempt_delay ""
	config_get garp_master_delay "$section" garp_master_delay ""
	config_get auth_type "$section" auth_type "none"
	config_get auth_pass "$section" auth_pass ""
	config_get unicast_src_ip "$section" unicast_src_ip ""

	[ -z "$interface" ] && { ha_log_warning "VIP $section has no interface"; return 1; }
	[ -z "$address" ] && [ -z "$address6" ] && { ha_log_warning "VIP $section has no address (IPv4 or IPv6)"; return 1; }
	[ -z "$vrid" ] && { ha_log_warning "VIP $section has no VRID"; return 1; }

	# Validate IPv6 address and prefix if set
	if [ -n "$address6" ]; then
		is_valid_ipv6 "$address6" || { ha_log_error "VIP $section: invalid IPv6 address (got: $address6)"; return 1; }
		case "$prefix6" in
			''|*[!0-9]*) ha_log_error "VIP $section: prefix6 must be a number (got: $prefix6)"; return 1 ;;
		esac
		[ "$prefix6" -lt 1 ] || [ "$prefix6" -gt 128 ] && { ha_log_error "VIP $section: prefix6 must be 1-128 (got: $prefix6)"; return 1; }
	fi

	# Validate numeric fields to prevent config injection
	case "$vrid" in
		''|*[!0-9]*) ha_log_error "VIP $section: VRID must be a number (got: $vrid)"; return 1 ;;
	esac
	[ "$vrid" -lt 1 ] || [ "$vrid" -gt 255 ] && { ha_log_error "VIP $section: VRID must be 1-255 (got: $vrid)"; return 1; }

	case "$priority" in
		''|*[!0-9]*) ha_log_error "VIP $section: priority must be a number (got: $priority)"; return 1 ;;
	esac
	[ "$priority" -lt 1 ] || [ "$priority" -gt 255 ] && { ha_log_error "VIP $section: priority must be 1-255 (got: $priority)"; return 1; }

	case "$advert_int" in
		''|*[!0-9]*) ha_log_error "VIP $section: advert_int must be a number (got: $advert_int)"; return 1 ;;
	esac

	# Convert netmask to CIDR notation for keepalived (only if IPv4 address set)
	local cidr=""
	if [ -n "$address" ]; then
		cidr=$(netmask_to_cidr "$netmask") || {
			ha_log_error "Cannot generate keepalived config: invalid netmask '$netmask'"
			return 1
		}
	fi

	# Collect track interfaces (list or single)
	_ha_list_result=""
	config_list_foreach "$section" track_interface _ha_list_collect
	track_ifaces="$_ha_list_result"
	if [ -z "$track_ifaces" ] && [ -n "$track_interface" ]; then
		track_ifaces="$track_interface"
	fi

	# Collect track scripts
	_ha_list_result=""
	config_list_foreach "$section" track_script _ha_list_collect
	track_scripts="$_ha_list_result"

	# Normalize auth_type
	case "$auth_type" in
		pass|PASS) auth_type="PASS" ;;
		ah|AH) auth_type="AH" ;;
	esac

	# Collect unicast peers
	_ha_list_result=""
	config_list_foreach "$section" unicast_peer _ha_list_collect
	unicast_peers="$_ha_list_result"

	if [ -n "$unicast_peers" ] && [ -z "$unicast_src_ip" ]; then
		ha_log_warning "VIP $section has unicast_peer but no unicast_src_ip"
	fi

	cat >> "$KEEPALIVED_CONF" <<EOF
vrrp_instance VI_${section} {
    state BACKUP
    interface $interface
    virtual_router_id $vrid
    priority $priority
    advert_int $advert_int
EOF

	_ha_write_vrrp_instance_options "$section"

	# Virtual IP address(es)
	# Note: Keepalived requires separate VRRP instances for IPv4 and IPv6
	# If both address and address6 are set, close this IPv4 instance and create a separate IPv6 one
	echo "    virtual_ipaddress {" >> "$KEEPALIVED_CONF"
	[ -n "$address" ] && echo "        $address/$cidr dev $interface" >> "$KEEPALIVED_CONF"
	cat >> "$KEEPALIVED_CONF" <<EOF
    }

    # Notify scripts for state changes
    notify_master "/bin/busybox env -i ACTION=MASTER TYPE=INSTANCE NAME=VI_${section} /sbin/hotplug-call keepalived"
    notify_backup "/bin/busybox env -i ACTION=BACKUP TYPE=INSTANCE NAME=VI_${section} /sbin/hotplug-call keepalived"
    notify_fault "/bin/busybox env -i ACTION=FAULT TYPE=INSTANCE NAME=VI_${section} /sbin/hotplug-call keepalived"
}

EOF

	# If IPv6 VIP is also configured, create a separate VRRP instance for it
	# (keepalived doesn't allow mixing IPv4 and IPv6 in same instance)
	if [ -n "$address6" ]; then
		local vrid6=$((vrid + 1))
		if [ "$vrid6" -gt 255 ]; then
			ha_log_error "VIP $section: IPv6 VRID would be $vrid6 (VRID+1), exceeds 255"
			return 1
		fi

		cat >> "$KEEPALIVED_CONF" <<EOF
vrrp_instance VI_${section}_v6 {
    state BACKUP
    interface $interface
    virtual_router_id $vrid6
    priority $priority
    advert_int $advert_int
EOF

		_ha_write_vrrp_instance_options "${section}_v6"

		# IPv6 Virtual IP
		cat >> "$KEEPALIVED_CONF" <<EOF
    virtual_ipaddress {
        $address6/$prefix6 dev $interface
    }

    # Notify scripts for state changes
    notify_master "/bin/busybox env -i ACTION=MASTER TYPE=INSTANCE NAME=VI_${section}_v6 /sbin/hotplug-call keepalived"
    notify_backup "/bin/busybox env -i ACTION=BACKUP TYPE=INSTANCE NAME=VI_${section}_v6 /sbin/hotplug-call keepalived"
    notify_fault "/bin/busybox env -i ACTION=FAULT TYPE=INSTANCE NAME=VI_${section}_v6 /sbin/hotplug-call keepalived"
}

EOF
	fi
}

# Generate owsync configuration file
ha_generate_owsync_conf() {
	local sync_method encryption_key sync_port sync_dir sync_interval owsync_log_level bind_address

	config_load ha-cluster
	config_get sync_method config sync_method "owsync"

	[ "$sync_method" != "owsync" ] && return 0

	config_get encryption_key config encryption_key ""
	config_get sync_port config sync_port "4321"
	config_get sync_dir config sync_dir "/etc/config"
	config_get sync_interval advanced sync_interval "30"
	config_get owsync_log_level advanced owsync_log_level "2"
	config_get bind_address config bind_address ""

	ha_log "Generating owsync configuration"

	# Generate config file with secure permissions
	rm -f "$OWSYNC_CONF"
	touch "$OWSYNC_CONF"
	chmod 0600 "$OWSYNC_CONF"

	# Use bind_address if configured, otherwise default to :: for dual-stack
	local owsync_bind="${bind_address:-::}"

	cat > "$OWSYNC_CONF" <<EOF
# Auto-generated by ha-cluster
# DO NOT EDIT - changes will be overwritten when HA cluster restarts
# Edit /etc/config/ha-cluster instead

# Network settings
bind_host=${owsync_bind}
port=${sync_port}

# Paths (OpenWrt-specific)
sync_dir=${sync_dir}
database=/etc/owsync/owsync.db

# Daemon settings
poll_interval=${sync_interval}
log_level=${owsync_log_level}

EOF

	# Security settings
	if [ -n "$encryption_key" ]; then
		echo "# Security: PSK encryption enabled" >> "$OWSYNC_CONF"
		echo "encryption_key=${encryption_key}" >> "$OWSYNC_CONF"
	else
		ha_log_warning "No encryption_key set - owsync will run without encryption"
		ha_log_warning "For production: Generate a key with 'owsync genkey' and set it in both nodes"
		ha_log_warning "Add to /etc/config/ha-cluster: option encryption_key '<your-key>'"
		echo "# Security: Plain mode (use only over secure VPN)" >> "$OWSYNC_CONF"
		echo "plain_mode=1" >> "$OWSYNC_CONF"
	fi
	echo "" >> "$OWSYNC_CONF"

	# Add peers
	echo "# Peers" >> "$OWSYNC_CONF"
	config_foreach ha_add_owsync_peer_conf peer
	echo "" >> "$OWSYNC_CONF"

	# Add includes (files to sync based on enabled services)
	echo "# Include patterns (sync these files)" >> "$OWSYNC_CONF"
	config_foreach ha_add_owsync_includes_conf service

	# Add excludes
	echo "" >> "$OWSYNC_CONF"
	echo "# Exclude patterns (never sync these)" >> "$OWSYNC_CONF"
	config_foreach ha_add_owsync_excludes_conf exclude

	ha_log "owsync configuration generated at $OWSYNC_CONF"
	return 0
}

# Add peer to owsync config (uses global port from config)
# Supports per-peer source_address for source address selection
ha_add_owsync_peer_conf() {
	local section="$1"
	local address source_address

	config_get address "$section" address
	config_get source_address "$section" source_address ""

	[ -z "$address" ] && return 0

	if [ -n "$source_address" ]; then
		echo "peer=${address},${source_address}" >> "$OWSYNC_CONF"
		ha_log_debug "owsync peer: $address (source: $source_address)"
	else
		echo "peer=${address}" >> "$OWSYNC_CONF"
		ha_log_debug "owsync peer: $address (no source specified)"
	fi
}

# Add includes from enabled services
ha_add_owsync_includes_conf() {
	local section="$1"
	local enabled

	config_get_bool enabled "$section" enabled 0
	[ "$enabled" -eq 0 ] && return 0

	config_list_foreach "$section" config_files ha_add_owsync_include_conf
}

ha_add_owsync_include_conf() {
	echo "include=$1" >> "$OWSYNC_CONF"
}

# Add excludes
ha_add_owsync_excludes_conf() {
	local section="$1"
	config_list_foreach "$section" file ha_add_owsync_exclude_conf
}

ha_add_owsync_exclude_conf() {
	echo "exclude=$1" >> "$OWSYNC_CONF"
}


# Generate lease-sync configuration (flat file for managed mode)
ha_generate_lease_sync_conf() {
	local dhcp_service_enabled lease_sync_enabled lease_sync_port encryption_key
	local sync_interval peer_timeout persist_interval log_level node_name bind_address

	config_load ha-cluster

	# Check if DHCP service has lease sync enabled
	config_get_bool dhcp_service_enabled dhcp enabled 0
	config_get_bool lease_sync_enabled dhcp sync_leases 0
	config_get lease_sync_port advanced lease_sync_port "5378"
	config_get sync_interval advanced lease_sync_interval "30"
	config_get peer_timeout advanced lease_sync_peer_timeout "120"
	config_get persist_interval advanced lease_sync_persist_interval "60"
	config_get log_level advanced lease_sync_log_level "2"
	config_get encryption_key config encryption_key ""
	config_get bind_address config bind_address ""
	node_name="$(cat /proc/sys/kernel/hostname)"

	[ "$dhcp_service_enabled" -eq 0 ] || [ "$lease_sync_enabled" -eq 0 ] && {
		ha_log_debug "DHCP lease sync disabled"
		return 0
	}

	ha_log "Generating lease-sync configuration"

	# Generate config file with secure permissions (for encryption key)
	rm -f "$LEASE_SYNC_CONF"
	touch "$LEASE_SYNC_CONF"
	chmod 0600 "$LEASE_SYNC_CONF"

	cat > "$LEASE_SYNC_CONF" <<EOF
# Auto-generated by ha-cluster
# DO NOT EDIT - changes will be overwritten when HA cluster restarts
# Edit /etc/config/ha-cluster instead

node_id=${node_name}
sync_port=${lease_sync_port}
sync_interval=${sync_interval}
peer_timeout=${peer_timeout}
persist_interval=${persist_interval}
log_level=${log_level}
EOF

	# Add bind_address if configured (prevents VIP from being used as source)
	if [ -n "$bind_address" ]; then
		echo "bind_address=${bind_address}" >> "$LEASE_SYNC_CONF"
		ha_log "lease-sync will bind to $bind_address"
	fi

	# Security settings: use encryption if key is available, otherwise plain mode
	if [ -n "$encryption_key" ]; then
		cat >> "$LEASE_SYNC_CONF" <<EOF

# Security: AES-256-GCM PSK encryption enabled
security_mode=encrypted
psk_key=${encryption_key}
EOF
		ha_log "lease-sync will use AES-256-GCM encryption"
	else
		cat >> "$LEASE_SYNC_CONF" <<EOF

# Security: Plain mode (use only over secure VPN)
# WARNING: Ensure network-layer security (WireGuard/IPsec) is configured!
security_mode=plain
plain_mode_acknowledged=1
EOF
		ha_log_warning "lease-sync running in plain mode - ensure network-layer security"
	fi

	echo "" >> "$LEASE_SYNC_CONF"

	# Add peers
	config_foreach ha_add_lease_sync_peer_flat peer

	ha_log "lease-sync configuration generated at $LEASE_SYNC_CONF"
	return 0
}

# Supports per-peer source_address for source address selection
ha_add_lease_sync_peer_flat() {
	local section="$1"
	local address source_address

	config_get address "$section" address
	config_get source_address "$section" source_address ""

	[ -z "$address" ] && return 0

	if [ -n "$source_address" ]; then
		echo "peer=${address},${source_address}" >> "$LEASE_SYNC_CONF"
		ha_log_debug "lease-sync peer: $address (source: $source_address)"
	else
		echo "peer=${address}" >> "$LEASE_SYNC_CONF"
		ha_log_debug "lease-sync peer: $address (no source specified)"
	fi
}

# Validate ha-cluster configuration
ha_validate_config() {
	local errors=0
	local vrid_list=""

	config_load ha-cluster

	# Check if enabled
	config_get_bool enabled config enabled 0
	[ "$enabled" -eq 0 ] && return 0

	# Validate VRIDs are unique
	config_foreach ha_check_vrid_unique vip

	# Check for peer configuration
	local peer_count=0
	config_foreach ha_count_peers peer
	[ "$peer_count" -eq 0 ] && {
		ha_log_warning "No peers configured - HA will not function"
	}

	return $errors
}

ha_check_vrid_unique() {
	local section="$1"
	local enabled vrid

	config_get_bool enabled "$section" enabled 0
	[ "$enabled" -eq 0 ] && return 0

	config_get vrid "$section" vrid
	[ -z "$vrid" ] && return 0

	echo "$vrid_list" | grep -qw "$vrid" && {
		ha_log_error "Duplicate VRID $vrid in section $section"
		return 1
	}

	vrid_list="$vrid_list $vrid"
}

ha_count_peers() {
	peer_count=$((peer_count + 1))
}

# Manage standalone services (disable/enable)
ha_manage_services() {
	local action="$1"  # "take_over" or "release"
	local state_file="/etc/ha-cluster/service_states"

	mkdir -p /etc/ha-cluster

	if [ "$action" = "take_over" ]; then
		# Save current state and disable standalone services
		ha_log "Taking over service management from standalone init scripts"

		# Clear previous state file
		rm -f "$state_file"

		for service in keepalived owsync lease-sync; do
			if [ -x "/etc/init.d/$service" ]; then
				# Save enabled state
				if /etc/init.d/$service enabled 2>/dev/null; then
					echo "$service=1" >> "$state_file"
				else
					echo "$service=0" >> "$state_file"
				fi

				# Stop and disable
				/etc/init.d/$service stop 2>/dev/null
				/etc/init.d/$service disable 2>/dev/null
				ha_log "Disabled standalone service: $service"
			fi
		done

	elif [ "$action" = "release" ]; then
		# Restore previous state
		ha_log "Releasing service management back to standalone init scripts"

		[ ! -f "$state_file" ] && return 0

		while IFS='=' read -r service was_enabled; do
			if [ -x "/etc/init.d/$service" ] && [ "$was_enabled" = "1" ]; then
				/etc/init.d/$service enable 2>/dev/null
				/etc/init.d/$service start 2>/dev/null
				ha_log "Restored standalone service: $service"
			fi
		done < "$state_file"

		rm -f "$state_file"
	fi
}

# State file for DHCP force settings (same pattern as service_states)
# Format: dhcp_section=previous_value (one per line)
# previous_value is empty string if option didn't exist, or "1" if it was set
HA_DHCP_FORCE_STATE="/etc/ha-cluster/dhcp_force_states"

# Sets dhcp.<section>.force='1' for all interfaces with VIPs
# Saves previous state to restore later
ha_configure_dhcp_force() {
	local dhcp_enabled lease_sync_enabled

	config_load ha-cluster
	config_get_bool dhcp_enabled dhcp enabled 0
	config_get_bool lease_sync_enabled dhcp sync_leases 0

	# First, restore any previously modified interfaces
	# This handles: VIP removed, reload, crash recovery
	# Must be done BEFORE clearing state file and BEFORE checking enabled flags
	# (so interfaces are restored even if DHCP sync is now disabled)
	ha_release_dhcp_force

	[ "$dhcp_enabled" -eq 0 ] && return 0
	[ "$lease_sync_enabled" -eq 0 ] && return 0

	ha_log "Configuring DHCP force option for HA operation"

	# Ensure directory exists (already done by ha_manage_services, but be safe)
	mkdir -p /etc/ha-cluster

	# Track processed interfaces to avoid duplicates
	_ha_dhcp_force_processed=""

	# Iterate over all vip sections to find VIP interfaces
	config_foreach _ha_configure_dhcp_force_callback vip

	# Commit if we made changes
	[ -f "$HA_DHCP_FORCE_STATE" ] && [ -s "$HA_DHCP_FORCE_STATE" ] && {
		uci commit dhcp
		ha_log "DHCP force configuration saved"
	}
}

# Callback for config_foreach to get interface from vip section
_ha_configure_dhcp_force_callback() {
	local section="$1"
	local interface enabled

	config_get_bool enabled "$section" enabled 0
	[ "$enabled" -eq 0 ] && return 0

	config_get interface "$section" interface
	[ -z "$interface" ] && return 0

	# Check if already processed (avoid duplicates)
	echo "$_ha_dhcp_force_processed" | grep -qw "$interface" && return 0
	_ha_dhcp_force_processed="$_ha_dhcp_force_processed $interface"

	_ha_configure_dhcp_force_for_interface "$interface"
}

# Helper to process one VIP interface
_ha_configure_dhcp_force_for_interface() {
	local iface="$1"
	local dhcp_section current_force

	# Find the dhcp section for this interface
	# uci show dhcp | grep "interface='lan'" returns "dhcp.lan.interface='lan'"
	# Use -F for fixed-string matching to prevent regex injection via $iface
	dhcp_section=$(uci show dhcp 2>/dev/null | grep -F ".interface='$iface'" | cut -d. -f2 | head -1)
	[ -z "$dhcp_section" ] && {
		ha_log_debug "No DHCP section found for interface $iface, skipping"
		return 0
	}

	# Save current state (empty string if not set)
	current_force=$(uci -q get "dhcp.$dhcp_section.force")

	# Only modify if not already set to 1
	if [ "$current_force" = "1" ]; then
		ha_log_debug "dhcp.$dhcp_section.force already enabled"
		# Don't save to state file - we didn't change it
		return 0
	fi

	# Save previous state and set new value
	echo "$dhcp_section=$current_force" >> "$HA_DHCP_FORCE_STATE"
	uci set "dhcp.$dhcp_section.force=1"
	ha_log "Enabled dhcp.$dhcp_section.force for HA operation"
}

# Reverts dhcp.*.force to previous state
ha_release_dhcp_force() {
	local dhcp_section previous_value

	[ ! -f "$HA_DHCP_FORCE_STATE" ] && return 0

	ha_log "Releasing DHCP force configuration"

	while IFS='=' read -r dhcp_section previous_value; do
		[ -z "$dhcp_section" ] && continue

		if [ -z "$previous_value" ]; then
			# Was not set before, delete it
			uci -q delete "dhcp.$dhcp_section.force"
			ha_log "Removed dhcp.$dhcp_section.force"
		else
			# Restore previous value
			uci set "dhcp.$dhcp_section.force=$previous_value"
			ha_log "Restored dhcp.$dhcp_section.force=$previous_value"
		fi
	done < "$HA_DHCP_FORCE_STATE"

	uci commit dhcp
	rm -f "$HA_DHCP_FORCE_STATE"
}

# Apply all configurations
ha_apply_config() {
	ha_log "Applying HA cluster configuration"

	# Validate first
	ha_validate_config || {
		ha_log_error "Configuration validation failed"
		return 1
	}

	# Take over service management from standalone init scripts
	ha_manage_services "take_over"

	# Configure DHCP force option for HA operation (allows DHCP servers on both nodes)
	ha_configure_dhcp_force

	# Generate configs - services will be started by ha-cluster init
	ha_generate_keepalived_conf
	ha_generate_owsync_conf
	ha_generate_lease_sync_conf

	ha_log "HA cluster configuration applied successfully"
	return 0
}

